### ISSUE TITLE
Random page displaying incorrect scores and votes

### ISSUE THREAD

**Issue by quentin-dev** [seirl/epiquote#15]
All the quotes on the random page have a score of either +1 or -1, all with only 1 vote.
For example : 
![Example](https://user-images.githubusercontent.com/20909347/43138720-13c909d2-8f50-11e8-84c8-c06b07db762f.png)

**Comment by seirl** [comment]
Nice catch. Fixed in 02b3fe35e48661801d8ca3fa05b108b9cfcdc7e5 (horribly)...
